version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./${PROJECT_DIRECTORY_NAME}:/var/www/html
    expose:
      - "80"
    ports:
      - ${NGINX_PORT}:80
    restart: always
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./${PROJECT_DIRECTORY_NAME}:/var/www/html

    ## --------------------------------------------
    ## | 4 : database server
    ## --------------------------------------------
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${PROJECT_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${PROJECT_DATABASE_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./host-vol-share/:/v-share/
    env_file:
      - .env
    ## --------------------------------------------
    ## | 5 : PhpMyAdmin
    ## --------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    expose:
      - '80'
      - '443'
    environment:
      - PMA_HOST=mysqldb
    volumes:
      - /sessions
    ports:
      - 8009:80


